GO
USE DB_FACTURACION
GO

-- Generado por Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   en:        2022-11-09 19:41:28 CST
--   sitio:      SQL Server 2012
--   tipo:      SQL Server 2012



CREATE TABLE CONTADOR 
    (
     ID_CONTADOR INTEGER NOT NULL , 
     ID_TIPO_CONTADOR INTEGER NOT NULL , 
     DPI INTEGER NOT NULL , 
     ID_TARIFA INTEGER NOT NULL , 
     DIRECCION_DESTINO VARCHAR (50) NOT NULL , 
     ID_MUNICIPIO INTEGER NOT NULL , 
     ID_DEPARTAMENTO INTEGER NOT NULL 
    )
GO

ALTER TABLE CONTADOR ADD CONSTRAINT CONTADOR_PK PRIMARY KEY CLUSTERED (ID_CONTADOR)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE DEPARTAMENTOS 
    (
     ID_DEPARTAMENTO INTEGER NOT NULL , 
     NOMBRE_DEPARTAMENTO VARCHAR (20) NOT NULL , 
     ID_REGION INTEGER NOT NULL 
    )
GO

ALTER TABLE DEPARTAMENTOS ADD CONSTRAINT DEPARTAMENTOS_PK PRIMARY KEY CLUSTERED (ID_DEPARTAMENTO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE FACTURA 
    (
     ID_FACTURA INTEGER IDENTITY(1,1) NOT NULL , 
     DPI INTEGER NOT NULL , 
     ID_CONTADOR INTEGER NOT NULL , 
     FECHA_GENERACION DATETIME DEFAULT GETDATE() NOT NULL , 
     CONSUMO_FINAL INTEGER NOT NULL , 
     FECHA_REGISTRO DATETIME NOT NULL , 
     PRECIO NUMERIC (10,2) NOT NULL 
    )
GO

ALTER TABLE FACTURA ADD CONSTRAINT FACTURA_PK PRIMARY KEY CLUSTERED (ID_FACTURA)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE HISTORIAL_MENSUAL 
    (
     ID_CONTADOR INTEGER NOT NULL , 
     FECHA_REGISTRO DATETIME DEFAULT GETDATE() NOT NULL , 
     LECTURA_ACTUAL INTEGER NOT NULL 
    )
GO

ALTER TABLE HISTORIAL_MENSUAL ADD CONSTRAINT CONSUMO_MENSUAL_PK PRIMARY KEY CLUSTERED (FECHA_REGISTRO, ID_CONTADOR)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE MUNICIPIOS 
    (
     ID_DEPARTAMENTO INTEGER NOT NULL , 
     ID_MUNICIPIO INTEGER NOT NULL , 
     NOMBRE_MUNICIPIO VARCHAR (50) NOT NULL , 
     ALUMBRADO_PUBLICO NUMERIC (10,2) NOT NULL 
    )
GO

ALTER TABLE MUNICIPIOS ADD CONSTRAINT MUNICIPIOS_PK PRIMARY KEY CLUSTERED (ID_MUNICIPIO, ID_DEPARTAMENTO)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE PERSONAS 
    (
     DPI INTEGER NOT NULL , 
     PRIMER_NOMBRE VARCHAR (20) NOT NULL , 
     SEGUNDO_NOMBRE VARCHAR (20) , 
     TERCER_NOMBRE VARCHAR (20) , 
     PRIMER_APELLIDO VARCHAR (20) NOT NULL , 
     SEGUNDO_APELLIDO VARCHAR (20) , 
     TERCER_APELLIDO VARCHAR (20) , 
     TELEFONO INTEGER NOT NULL , 
     DIRECCION_RESIDENCIA VARCHAR (50) NOT NULL , 
     EMAIL VARCHAR (50) NOT NULL , 
     PASSWORD VARCHAR (50) , 
     ID_ROL INTEGER NOT NULL , 
     ID_MUNICIPIO INTEGER NOT NULL , 
     ID_DEPARTAMENTO INTEGER NOT NULL 
    )
GO

ALTER TABLE PERSONAS ADD CONSTRAINT PERSONAS_PK PRIMARY KEY CLUSTERED (DPI)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE REGIONES 
    (
     ID_REGION INTEGER NOT NULL , 
     NOMBRE_REGION VARCHAR (20) NOT NULL 
    )
GO

ALTER TABLE REGIONES ADD CONSTRAINT REGIONES_PK PRIMARY KEY CLUSTERED (ID_REGION)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE ROLES 
    (
     ID_ROL INTEGER NOT NULL , 
     NOMBRE_ROL VARCHAR (20) NOT NULL 
    )
GO

ALTER TABLE ROLES ADD CONSTRAINT ROLES_PK PRIMARY KEY CLUSTERED (ID_ROL)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE TIPO_CONTADOR 
    (
     ID_TIPO_CONTADOR INTEGER NOT NULL , 
     NOMBRE_TIPO_CONTADOR VARCHAR (20) NOT NULL 
    )
GO

ALTER TABLE TIPO_CONTADOR ADD CONSTRAINT TIPO_CONTADOR_PK PRIMARY KEY CLUSTERED (ID_TIPO_CONTADOR)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE TIPO_TARIFAS 
    (
     ID_TARIFA INTEGER NOT NULL , 
     TIPO_TARIFA VARCHAR (20) NOT NULL , 
     PRECIO DECIMAL (10,2) NOT NULL 
    )
GO

ALTER TABLE TIPO_TARIFAS ADD CONSTRAINT TIPO_TARIFAS_PK PRIMARY KEY CLUSTERED (ID_TARIFA)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

ALTER TABLE CONTADOR 
    ADD CONSTRAINT CONTADOR_MUNICIPIOS_FK FOREIGN KEY 
    ( 
     ID_MUNICIPIO, 
     ID_DEPARTAMENTO
    ) 
    REFERENCES MUNICIPIOS 
    ( 
     ID_MUNICIPIO , 
     ID_DEPARTAMENTO 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CONTADOR 
    ADD CONSTRAINT CONTADOR_PERSONAS_FK FOREIGN KEY 
    ( 
     DPI
    ) 
    REFERENCES PERSONAS 
    ( 
     DPI 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CONTADOR 
    ADD CONSTRAINT CONTADOR_TIPO_CONTADOR_FK FOREIGN KEY 
    ( 
     ID_TIPO_CONTADOR
    ) 
    REFERENCES TIPO_CONTADOR 
    ( 
     ID_TIPO_CONTADOR 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE CONTADOR 
    ADD CONSTRAINT CONTADOR_TIPO_TARIFAS_FK FOREIGN KEY 
    ( 
     ID_TARIFA
    ) 
    REFERENCES TIPO_TARIFAS 
    ( 
     ID_TARIFA 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE DEPARTAMENTOS 
    ADD CONSTRAINT DEPARTAMENTOS_REGIONES_FK FOREIGN KEY 
    ( 
     ID_REGION
    ) 
    REFERENCES REGIONES 
    ( 
     ID_REGION 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE FACTURA 
    ADD CONSTRAINT FACTURA_HISTORIAL_MENSUAL_FK FOREIGN KEY 
    ( 
     FECHA_REGISTRO, 
     ID_CONTADOR
    ) 
    REFERENCES HISTORIAL_MENSUAL 
    ( 
     FECHA_REGISTRO , 
     ID_CONTADOR 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE FACTURA 
    ADD CONSTRAINT FACTURA_PERSONAS_FK FOREIGN KEY 
    ( 
     DPI
    ) 
    REFERENCES PERSONAS 
    ( 
     DPI 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE HISTORIAL_MENSUAL 
    ADD CONSTRAINT HISTORIAL_MENSUAL_CONTADOR_FK FOREIGN KEY 
    ( 
     ID_CONTADOR
    ) 
    REFERENCES CONTADOR 
    ( 
     ID_CONTADOR 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE MUNICIPIOS 
    ADD CONSTRAINT MUNICIPIOS_DEPARTAMENTOS_FK FOREIGN KEY 
    ( 
     ID_DEPARTAMENTO
    ) 
    REFERENCES DEPARTAMENTOS 
    ( 
     ID_DEPARTAMENTO 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE PERSONAS 
    ADD CONSTRAINT PERSONAS_MUNICIPIOS_FK FOREIGN KEY 
    ( 
     ID_MUNICIPIO, 
     ID_DEPARTAMENTO
    ) 
    REFERENCES MUNICIPIOS 
    ( 
     ID_MUNICIPIO , 
     ID_DEPARTAMENTO 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE PERSONAS 
    ADD CONSTRAINT PERSONAS_ROLES_FK FOREIGN KEY 
    ( 
     ID_ROL
    ) 
    REFERENCES ROLES 
    ( 
     ID_ROL 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
